prgrms-web-devcourse-final-project/WEB3_4_PlayON_BE

.github/workflows/ai-pr-summary.yml
.github/workflows/test.yml

main 브랜치에는 dev 브랜치를 통해서만 병합되게 할 예정이라
해당 내용은 dev 브랜치에만 적용

Gemini AI PR 요약과 PR시 테스트 진행하는 깃허브 액션

---

.gitignore
build.gradle
src/main/java/com/ll/playon/domain/image/entity/Image.java
src/main/java/com/ll/playon/domain/image/mapper/ImageMapper.java
src/main/java/com/ll/playon/domain/image/repository/ImageRepository.java
src/main/java/com/ll/playon/domain/image/service/ImageService.java
src/main/java/com/ll/playon/domain/image/type/ImageType.java
src/main/java/com/ll/playon/domain/party/party/controller/PartyController.java
src/main/java/com/ll/playon/global/aws/s3/S3Config.java
src/main/java/com/ll/playon/global/aws/s3/S3Service.java
src/main/java/com/ll/playon/global/aws/s3/S3Util.java
src/main/java/com/ll/playon/global/exceptions/ErrorCode.java
src/main/resources/application.yml

#5 
- S3 이미지 관련 작업 완료
- DB와 연동할 ImageService 기능 구현

[FEAT] S3 이미지 작업 및 이미지 DB 작업 일부 추가

---

src/main/java/com/ll/playon/domain/party/party/controller/PartyController.java
src/main/java/com/ll/playon/domain/party/party/dto/request/PostPartyRequest.java
src/main/java/com/ll/playon/domain/party/party/dto/request/PostPartyTagRequest.java
src/main/java/com/ll/playon/domain/party/party/dto/response/PostPartyResponse.java
src/main/java/com/ll/playon/domain/party/party/dto/response/PostPartyTagResponse.java
src/main/java/com/ll/playon/domain/party/party/entity/Party.java
src/main/java/com/ll/playon/domain/party/party/entity/PartyTag.java
src/main/java/com/ll/playon/domain/party/party/mapper/PartyMapper.java
src/main/java/com/ll/playon/domain/party/party/mapper/PartyTagMapper.java
src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
src/main/java/com/ll/playon/domain/party/party/repository/PartyTagRepository.java
src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
src/main/java/com/ll/playon/global/exceptions/ErrorCode.java
src/main/java/com/ll/playon/global/exceptions/handler/GlobalExceptionHandler.java
src/main/java/com/ll/playon/global/type/TagType.java
src/main/java/com/ll/playon/global/type/TagValue.java
src/main/java/com/ll/playon/standard/util/TagUtil.java

closes #13
- Party, PartyTag 엔티티 추가
- 태그 다중 선택 가능하도록 연관관계 설정
- TagType 추가
- TagValue 추가
- 파티 생성 기능 추가
-  POSTMAN으로 테스트 진행

[FEAT] Party 및 태그 Entity, DTO 구현, 파티 생성

---

src/main/java/com/ll/playon/domain/party/party/controller/PartyController.java
src/main/java/com/ll/playon/domain/party/party/dto/request/PartyTagRequest.java
src/main/java/com/ll/playon/domain/party/party/dto/request/PutPartyRequest.java
src/main/java/com/ll/playon/domain/party/party/dto/response/PartyTagResponse.java
src/main/java/com/ll/playon/domain/party/party/dto/response/PutPartyResponse.java
src/main/java/com/ll/playon/domain/party/party/entity/Party.java
src/main/java/com/ll/playon/domain/party/party/entity/PartyMember.java
src/main/java/com/ll/playon/domain/party/party/entity/PartyTag.java
src/main/java/com/ll/playon/domain/party/party/mapper/PartyMemberMapper.java
src/main/java/com/ll/playon/domain/party/party/repository/PartyMemberRepository.java
src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
src/main/java/com/ll/playon/domain/party/party/service/PartyTagService.java
src/main/java/com/ll/playon/domain/party/party/type/PartyRole.java
src/main/java/com/ll/playon/global/exceptions/ErrorCode.java
src/main/java/com/ll/playon/global/security/UserContext.java
src/main/java/com/ll/playon/global/type/TagValue.java

closes #19 
- 파티 수정 기능 구현 완료
- `PostMan` 을 통한 1차 테스트 완료

[FEAT] 파티 수정

---

src/main/java/com/ll/playon/domain/party/party/controller/PartyController.java
src/main/java/com/ll/playon/domain/party/party/entity/Party.java
src/main/java/com/ll/playon/domain/party/party/mapper/PartyTagMapper.java
src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
src/main/java/com/ll/playon/domain/party/party/type/PartyStatus.java

close #21 
- 파티 삭제 구현 완료
- 도메인 URL 관련 변경
- 기존 코드 일부 리팩토링

[FEAT] 파티 삭제

---

src/main/java/com/ll/playon/domain/party/party/controller/PartyController.java
src/main/java/com/ll/playon/domain/party/party/dto/PartyDetailMemberDto.java
src/main/java/com/ll/playon/domain/party/party/dto/PartyDetailTagDto.java
src/main/java/com/ll/playon/domain/party/party/dto/response/GetPartyDetailResponse.java
src/main/java/com/ll/playon/domain/party/party/entity/Party.java
src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
src/main/java/com/ll/playon/global/exceptions/ErrorCode.java
src/main/java/com/ll/playon/global/initData/BaseInitData.java

close #24 
- 파티 상세 조회 구현
- url 도메인 변경
- 어울리지 않는 필드명 변경
- **PostMan** 테스트 진행

[FEAT] 파티 상세 조회

---

src/main/java/com/ll/playon/domain/guild/guildMember/controller/GuildMemberController.java
src/main/java/com/ll/playon/domain/guild/guildMember/dto/request/InviteMemberRequest.java
src/main/java/com/ll/playon/domain/guild/guildMember/repository/GuildMemberRepository.java
src/main/java/com/ll/playon/domain/guild/guildMember/service/GuildMemberService.java
src/test/java/com/ll/playon/domain/guild/guildJoinRequest/controller/GuildJoinRequestControllerTest.java
src/test/java/com/ll/playon/domain/guild/guildMember/controller/GuildMemberControllerTest.java

[FEAT] 닉네임 기반 길드 멤버 초대 기능 구현

---

src/main/java/com/ll/playon/domain/game/game/controller/GameController.java
src/main/java/com/ll/playon/domain/game/game/dto/GameRankDto.java
src/main/java/com/ll/playon/domain/game/game/repository/GameRepository.java
src/main/java/com/ll/playon/domain/game/game/service/GameService.java
src/main/java/com/ll/playon/domain/member/service/MemberService.java
src/main/java/com/ll/playon/global/initData/TestInitData.java
src/main/java/com/ll/playon/global/openFeign/SteamStoreClient.java
src/main/java/com/ll/playon/global/openFeign/dto/GameItem.java
src/main/java/com/ll/playon/global/openFeign/dto/SteamSearchResponse.java
src/main/java/com/ll/playon/global/steamAPI/SteamAPI.java
src/test/java/com/ll/playon/domain/game/controller/GameControllerTest.java
src/test/java/com/ll/playon/domain/member/controller/MemberControllerTest.java

1. 스팀 인기순위는 멀티플레이 게임 기준으로 받아옵니다. (40개)
2. 해당 리스트에서 사용자가 소유하지 않고 선호하는 장르에 해당하는 게임을 추천해줍니다.

[FEAT] (메인 페이지) 스팀 인기순위 및 사용자 맞춤 게임 추천

---

src/main/java/com/ll/playon/domain/game/game/controller/GameController.java
src/main/java/com/ll/playon/domain/game/game/entity/SteamGenre.java
src/main/java/com/ll/playon/domain/game/game/entity/SteamImage.java
src/main/java/com/ll/playon/domain/game/game/entity/SteamMovie.java
src/main/java/com/ll/playon/domain/game/game/service/GameService.java
src/main/java/com/ll/playon/global/openFeign/SteamStoreClient.java
src/main/java/com/ll/playon/global/openFeign/dto/gameDetail/Category.java
src/main/java/com/ll/playon/global/openFeign/dto/gameDetail/GameDetail2.java
src/main/java/com/ll/playon/global/openFeign/dto/gameDetail/GameDetailDeserializer2.java
src/main/java/com/ll/playon/global/openFeign/dto/gameDetail/GameDetailWrapper2.java
src/main/java/com/ll/playon/global/openFeign/dto/gameDetail/Movie.java
src/main/java/com/ll/playon/global/openFeign/dto/gameDetail/Mp4.java
src/main/java/com/ll/playon/global/openFeign/dto/gameDetail/Platform.java
src/main/java/com/ll/playon/global/openFeign/dto/gameDetail/ReleaseDate.java
src/main/java/com/ll/playon/global/openFeign/dto/gameDetail/Screenshot.java
src/main/java/com/ll/playon/global/openFeign/dto/gameDetail/SteamGameDetailResponse2.java
src/main/java/com/ll/playon/global/steamAPI/SteamAPI.java

게임 조회시 DB 조회 후 없으면 스팀 API 에서 받아와 갱신하는 로직
이후 필요한 곳에 적용 예정

[FEAT] 게임 데이터 갱신 로직

---

src/main/java/com/ll/playon/domain/game/game/batch/processor/SteamGameProcessor.java
src/main/java/com/ll/playon/domain/guild/guild/controller/GuildController.java
src/main/java/com/ll/playon/domain/guild/guild/dto/request/GetGuildListRequest.java
src/main/java/com/ll/playon/domain/guild/guild/dto/request/PutGuildRequest.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/GetGuildDetailResponse.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/GetGuildListResponse.java
src/main/java/com/ll/playon/domain/guild/guild/entity/Guild.java
src/main/java/com/ll/playon/domain/guild/guild/repository/GuildRepositoryCustom.java
src/main/java/com/ll/playon/domain/guild/guild/repository/GuildRepositoryImpl.java
src/main/java/com/ll/playon/domain/guild/guild/service/GuildService.java
src/main/java/com/ll/playon/global/initData/BaseInitData.java
src/test/java/com/ll/playon/domain/guild/guild/controller/GuildControllerTest.java
src/test/java/com/ll/playon/domain/guild/guild/service/GuildServiceTest.java

[REFACTOR] 길드 게임 엔티티 연결 & 길드 검색 수정

---

src/main/java/com/ll/playon/domain/game/game/batch/processor/SteamGameProcessor.java

게임 이용등급 파싱과정 수정
0 - 14 -> 0
15 - 17 -> 15
18 - -> 18
관련이슈
#60

[REFACTOR] 게임 이용등급 수정

---

src/main/java/com/ll/playon/domain/game/game/entity/WeeklyPopularGame.java
src/main/java/com/ll/playon/domain/game/game/service/GameService.java
src/main/java/com/ll/playon/domain/game/scheduler/repository/WeeklyGameRepository.java
src/main/java/com/ll/playon/domain/game/scheduler/scheduler/GameScheduler.java
src/main/java/com/ll/playon/domain/guild/guild/dto/request/GetGuildListRequest.java
src/main/java/com/ll/playon/domain/guild/guild/dto/request/PostGuildRequest.java
src/main/java/com/ll/playon/domain/guild/guild/dto/request/PutGuildRequest.java
src/main/java/com/ll/playon/domain/guild/guild/repository/GuildRepositoryImpl.java
src/main/java/com/ll/playon/domain/guild/guild/service/GuildService.java
src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
src/main/java/com/ll/playon/global/initData/BaseInitData.java
src/test/java/com/ll/playon/domain/guild/guild/controller/GuildControllerTest.java
src/test/java/com/ll/playon/domain/guild/guild/service/GuildServiceTest.java

기존 SteamGame id 사용에서 통일성 위해 appid로 변경

[REFACTOR] 길드 게임 엔티티사용 수정

---

src/main/java/com/ll/playon/domain/game/batch/config/BatchConfig.java
src/main/java/com/ll/playon/domain/game/batch/controller/BatchJobController.java
src/main/java/com/ll/playon/domain/game/batch/processor/SteamGameProcessor.java
src/main/java/com/ll/playon/domain/game/batch/reader/SteamCsvReaderConfig.java
src/main/java/com/ll/playon/domain/game/batch/writer/SteamGameWriterConfig.java
src/main/java/com/ll/playon/domain/game/game/controller/GameController.java
src/main/java/com/ll/playon/domain/game/game/dto/response/GetRecommendedGameResponse.java
src/main/java/com/ll/playon/domain/game/game/service/GameService.java
src/main/java/com/ll/playon/domain/guild/guild/controller/GuildController.java
src/main/java/com/ll/playon/domain/guild/guild/entity/Guild.java
src/main/java/com/ll/playon/domain/member/controller/MemberController.java
src/main/java/com/ll/playon/domain/party/party/repository/PartyMemberRepository.java
src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java

내가 참여한 파티를 기준으로 함께 참여했던 유저들을 추적
그 유저들이 참여한 다른 파티에서 진행된 게임을 기반으로 추천
공개+ 완료상태의 파티만 대상으로 필터링
중복 게임 제거 후 최신순으로 정렬 최대 limit 개수만 반환 -> 기본값 4

[FEAT] 최근 함께 파티한 유저의 게임

---

src/main/java/com/ll/playon/domain/game/game/dto/GameListResponse.java
src/main/java/com/ll/playon/domain/game/game/service/GameService.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/GetGuildDetailResponse.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/GetGuildListResponse.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/GetPopularGuildResponse.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/PostGuildResponse.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/PutGuildResponse.java
src/main/java/com/ll/playon/domain/member/service/MemberService.java
src/test/java/com/ll/playon/domain/member/controller/MemberControllerTest.java

- 태그 응답을 객체 전체가 아닌 값만 전달
- 게임 장르 명칭을 일관되게 통일 gameGenres -> genres

[REFACTOR] 응답 구조 개선

---

src/main/java/com/ll/playon/domain/guild/guildBoard/controller/GuildBoardController.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/GuildBoardCommentDto.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/request/GuildBoardCommentCreateRequest.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/request/GuildBoardCommentUpdateRequest.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/request/GuildBoardCreateRequest.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/request/GuildBoardUpdateRequest.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/response/GuildBoardCommentCreateResponse.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/response/GuildBoardCreateResponse.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/response/GuildBoardDetailResponse.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/response/GuildBoardLikeToggleResponse.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/response/GuildBoardSummaryResponse.java
src/main/java/com/ll/playon/domain/guild/guildBoard/entity/GuildBoard.java
src/main/java/com/ll/playon/domain/guild/guildBoard/entity/GuildBoardComment.java
src/main/java/com/ll/playon/domain/guild/guildBoard/entity/GuildBoardLike.java
src/main/java/com/ll/playon/domain/guild/guildBoard/enums/BoardSortType.java
src/main/java/com/ll/playon/domain/guild/guildBoard/enums/BoardTag.java
src/main/java/com/ll/playon/domain/guild/guildBoard/repository/GuildBoardCommentRepository.java
src/main/java/com/ll/playon/domain/guild/guildBoard/repository/GuildBoardLikeRepository.java
src/main/java/com/ll/playon/domain/guild/guildBoard/repository/GuildBoardRepository.java
src/main/java/com/ll/playon/domain/guild/guildBoard/service/GuildBoardService.java
src/main/java/com/ll/playon/global/exceptions/ErrorCode.java
src/test/java/com/ll/playon/domain/guild/guildBoard/controller/GuildBoardControllerTest.java

**🧱 게시판 기능 전체 구현 완료**
1. 게시글 기능
- 게시글 전체 조회 (정렬 + 태그 + 키워드 검색)
- 게시글 작성 (길드장+운영진만 공지 작성 가능, 전체멤버 자유, 게임관련 작성가능)
- 게시글 수정 / 삭제 (작성자만 가능)
- 게시글 상세 보기 (조회수 증가 포함)
2. 게시글 좋아요 기능
- 좋아요 토글 (좋아요/취소)
- 좋아요 수 갱신 및 중복 방지 처리
3. 댓글 기능
- 댓글 작성 / 수정 / 삭제
- 본인만 수정 및 삭제 가능
✅ 테스트 코드 준비 완료 (GuildBoardControllerTest)

[FEAT] 길드 게시판 기능 구현

---

src/main/java/com/ll/playon/domain/game/game/entity/SteamGame.java

[REFACTOR] about_the_game 데이터 타입 수정
- 기존 : TEXT
- 변경 : LONGTEXT

[REFACTOR] about_the_game 데이터 타입 수정

---

src/main/java/com/ll/playon/domain/game/game/controller/GameController.java
src/main/java/com/ll/playon/domain/game/game/service/GameService.java
src/main/java/com/ll/playon/domain/member/controller/MemberController.java
src/main/java/com/ll/playon/domain/member/entity/enums/PlayStyle.java
src/main/java/com/ll/playon/domain/member/service/MemberService.java
src/main/java/com/ll/playon/domain/title/service/TitleEvaluator.java

사용자가 소유한 스팀 게임을 갱신하는 기능과
사용자 엔티티 설계가 프론트와 다른 부분을 수정하였습니다.

[FEAT] 사용자 스팀 게임 갱신 기능 및 사용자 엔티티 수정

---

src/main/java/com/ll/playon/domain/guild/guildBoard/controller/GuildBoardController.java

GuildBoardController 길드 게시판 이미지 업로드용 Presigned URL API 추가

[FEAT] 길드 게시판 이미지 업로드용 Presigned URL API 추가

---

src/main/resources/application-test.yml

[FIX] test 코드 실패 에러 수정
- application-test.yml에 내용 추가

[FIX] test 코드 실패 에러 수정

---

.github/workflows/deploy.yml

* 현재 테스트 확인 용으로 dev 브랜치로 지정
* 추후 main 브랜치로 변경 예정

[FEAT] deploy.yml 추가

---

.github/workflows/deploy.yml
Dockerfile

[FIX] deploy.yml 빌드 에러 수정
- Dockerfile 추가

[FIX] deploy.yml 빌드 에러 수정

---

.github/workflows/deploy.yml

[REFACTOR] DockerHub 기반 배포로 리팩토링
- 기존 : tar 기반 -> 변경 : DockerHub 기반

[REFACTOR] DockerHub 기반 배포로 리팩토링

---

.github/workflows/deploy.yml

[REFACTOR] dev 브랜치 -> main 브랜치 수정
* 최초 작업으로 인한 dev 브랜치로 시작
* 배포 성공하였으므로 이후 main 브랜치로 변경

[REFACTOR] dev 브랜치 -> main 브랜치 수정

---

src/main/java/com/ll/playon/domain/game/game/controller/GameController.java
src/main/java/com/ll/playon/domain/guild/guildBoard/controller/GuildBoardController.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/response/GetGuildBoardNoticeResponse.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/response/GetGuildBoardPreviewResponse.java
src/main/java/com/ll/playon/domain/guild/guildBoard/repository/GuildBoardRepository.java
src/main/java/com/ll/playon/domain/guild/guildBoard/service/GuildBoardService.java

- 길드 회원만 확인가능
- 공지 2개
- 최신글 4개
#104

[FEAT] 길드 상세페이지 공지/최신글

---

.github/workflows/test.yml

[FIX] dev 브랜치 내용 main 브랜치로 병합 문제 해결

[FIX] dev 브랜치 내용 main 브랜치로 병합 문제 해결

---

src/main/java/com/ll/playon/domain/member/dto/MemberDetailDto.java
src/main/java/com/ll/playon/global/initData/BaseInitData.java
src/main/java/com/ll/playon/global/type/TagValue.java
src/test/java/com/ll/playon/domain/guild/guild/controller/GuildControllerTest.java

UI 에 맞게 태그값 수정하고 관련 테스트와 샘플 데이터 생성 부분 수정했습니다!

[REFACTOR] 태그값 수정

---

src/main/java/com/ll/playon/domain/party/party/controller/PartyController.java

<br/>
<br/>
<br/>
- 기존 `GET` 에서 `POST` 로 변경

[FIX] 파티 리스트 조회 HTTP 요청 방식 변경

---

src/main/java/com/ll/playon/domain/guild/guild/controller/GuildController.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/GetGuildManageDetailResponse.java
src/main/java/com/ll/playon/domain/guild/guild/repository/GuildRepository.java
src/main/java/com/ll/playon/domain/guild/guild/service/GuildService.java
src/main/java/com/ll/playon/domain/guild/guildMember/entity/GuildMember.java
src/main/java/com/ll/playon/domain/guild/guildMember/repository/GuildMemberRepository.java
src/test/java/com/ll/playon/domain/guild/guild/service/GuildServiceTest.java

<br/>
<br/>
<br/>
- 관라자 페이지 상세조회
- 운영진, 길드장만 접근 가능 (권한 체크 필요)
- 일반 상세페이지랑 응답값이 다름
- 일반 유저가 접근 시 GUILD_NO_PERMISSION
- 일반 상세조회
- 모든 사람 접근가능
- 길드내에서의 역할 필요 -> UI구성위해
- 길드 가입자 아닌경우 GUEST

[FEAT] 길드 상세 조회 일반/관리자

---

src/main/java/com/ll/playon/domain/guild/guild/controller/GuildController.java
src/main/java/com/ll/playon/domain/guild/guild/dto/request/PostGuildRequest.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/PostGuildResponse.java
src/main/java/com/ll/playon/domain/guild/guild/entity/Guild.java
src/main/java/com/ll/playon/domain/guild/guild/service/GuildService.java
src/test/java/com/ll/playon/domain/guild/guild/controller/GuildControllerTest.java

[FIX] 길드 생성 태그 수정

---

src/main/java/com/ll/playon/domain/guild/guild/controller/GuildController.java
src/main/java/com/ll/playon/domain/guild/guild/repository/GuildMemberRepositoryCustom.java
src/main/java/com/ll/playon/domain/guild/guild/repository/GuildMemberRepositoryCustomImpl.java
src/main/java/com/ll/playon/domain/guild/guild/service/GuildService.java
src/main/java/com/ll/playon/global/initData/BaseInitData.java

[FEAT] 길드 멤버 조회

---

src/main/java/com/ll/playon/domain/guild/guild/controller/GuildController.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/getGuildMemberResponse.java
src/main/java/com/ll/playon/domain/guild/guild/repository/GuildMemberRepositoryCustom.java
src/main/java/com/ll/playon/domain/guild/guild/repository/GuildMemberRepositoryCustomImpl.java
src/main/java/com/ll/playon/domain/guild/guild/service/GuildService.java
src/main/java/com/ll/playon/global/initData/BaseInitData.java

[REFACTOR] 길드 상세페이지 멤버 조회 응답데이터 추가

---

src/main/java/com/ll/playon/domain/guild/guild/controller/GuildController.java
src/main/java/com/ll/playon/domain/guild/guild/dto/request/GetGuildListRequest.java
src/main/java/com/ll/playon/domain/guild/guild/dto/request/PutGuildRequest.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/GetGuildDetailResponse.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/GetGuildListResponse.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/GetGuildManageDetailResponse.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/GetPopularGuildResponse.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/GetRecommendGuildResponse.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/PostGuildResponse.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/PutGuildResponse.java
src/main/java/com/ll/playon/domain/guild/guild/entity/Guild.java
src/main/java/com/ll/playon/domain/guild/guild/repository/GuildRepositoryImpl.java
src/main/java/com/ll/playon/domain/guild/guild/service/GuildService.java
src/main/java/com/ll/playon/global/initData/BaseInitData.java
src/main/java/com/ll/playon/global/validation/FileValidator.java

[REFACTOR] 응답 구조 수정, 이미지 업로드 로직 수정

---

src/main/java/com/ll/playon/domain/guild/guild/controller/GuildController.java
src/main/java/com/ll/playon/domain/guild/guild/service/GuildService.java
src/main/java/com/ll/playon/domain/guild/guildBoard/controller/GuildBoardController.java
src/main/java/com/ll/playon/domain/image/listener/ImageEventListener.java
src/main/java/com/ll/playon/domain/image/type/ImageType.java
src/main/java/com/ll/playon/global/aws/s3/S3Util.java
src/test/java/com/ll/playon/domain/guild/guild/service/GuildServiceTest.java

[REFACTOR] 길드 이미지 업로드, 수정, 삭제 로직 수정

---

src/main/java/com/ll/playon/domain/chat/controller/ChatController.java
src/main/java/com/ll/playon/domain/chat/controller/ChatMessageController.java
src/main/java/com/ll/playon/domain/chat/dto/ChatMessageDto.java
src/main/java/com/ll/playon/domain/chat/service/ChatMessageService.java
src/main/java/com/ll/playon/domain/chat/service/ChatService.java
src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
src/main/resources/static/chat-test2.html

[REFACTOR] 채팅 시 칭호 연결

---

src/main/java/com/ll/playon/domain/party/party/dto/response/GetPartyResponse.java

<br/>
<br/>
<br/>
- 프론트 측의 요구에 맞게 파티 응답 데이터 필드 추가

[REFACTOR] 파티 리스트 응답 데이터 수정

---

src/main/java/com/ll/playon/domain/guild/guildBoard/controller/GuildBoardController.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/request/GuildBoardCreateRequest.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/request/GuildBoardUpdateRequest.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/response/GuildBoardCreateResponse.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/response/GuildBoardUpdateResponse.java
src/main/java/com/ll/playon/domain/guild/guildBoard/service/GuildBoardService.java
src/test/java/com/ll/playon/domain/guild/guildBoard/controller/GuildBoardControllerTest.java

<br/>
<br/>
<br/>
- [FEAT] 게시글 생성/수정 시 presigned URL 반환 및 이미지 URL 저장 로직 추가
- [FIX] 길드게시판 게시글 수정 테스트코드 수정

[FEAT] 게시글 생성/수정 시 presigned URL 반환 및 이미지 URL 저장 로직 추가

---

.gitignore

[FIX] db.old 파일 제거

---

src/main/java/com/ll/playon/domain/image/repository/ImageRepository.java
src/main/java/com/ll/playon/domain/image/service/ImageService.java
src/main/java/com/ll/playon/global/aws/s3/S3Service.java

<br/>
<br/>
<br/>
- 이미지 수정 쪽 버그 수정

[FIX] 이미지 삭제 안되던 버그 수정

---

src/main/java/com/ll/playon/global/app/AppConfig.java

[REFACTOR] ec2 주소로 변경

---

src/main/java/com/ll/playon/global/app/AppConfig.java

[REFACTOR] ec2 주소로 변경 (#164)

---

src/main/java/com/ll/playon/domain/guild/guild/controller/GuildController.java
src/main/java/com/ll/playon/domain/guild/guild/dto/request/PostImageUrlRequest.java
src/main/java/com/ll/playon/domain/guild/guild/entity/Guild.java
src/main/java/com/ll/playon/domain/guild/guild/service/GuildService.java
src/main/java/com/ll/playon/domain/image/service/ImageService.java
src/main/java/com/ll/playon/domain/party/partyLog/controller/PartyLogController.java
src/main/java/com/ll/playon/domain/party/partyLog/dto/request/PostImageUrlRequest.java
src/main/java/com/ll/playon/domain/party/partyLog/service/PartyLogService.java

<br/>
<br/>
<br/>
- 이미지 URL 저장 시 "" 제거
- URL 파라미터를 String → DTO로 변경하여 요청값 파싱 처리

[FIX] 길드/파티 이미지 업로드 "" 문제 해결

---

src/main/java/com/ll/playon/global/initData/BaseInitData.java

<br/>
<br/>
<br/>
- `PartyMember` 를 `BaseInit` 에 추가

[FIX] PartyMember BaseInit에 추가

---

src/main/java/com/ll/playon/domain/guild/guild/controller/GuildController.java
src/main/java/com/ll/playon/domain/guild/guild/dto/request/PostImageUrlRequest.java
src/main/java/com/ll/playon/domain/guild/guild/entity/Guild.java
src/main/java/com/ll/playon/domain/guild/guild/service/GuildService.java
src/main/java/com/ll/playon/domain/guild/guildJoinRequest/dto/response/GuildJoinRequestResponse.java
src/main/java/com/ll/playon/domain/image/service/ImageService.java
src/main/java/com/ll/playon/domain/party/partyLog/controller/PartyLogController.java
src/main/java/com/ll/playon/domain/party/partyLog/dto/request/PostImageUrlRequest.java
src/main/java/com/ll/playon/domain/party/partyLog/service/PartyLogService.java
src/main/java/com/ll/playon/global/app/AppConfig.java
src/main/java/com/ll/playon/global/initData/BaseInitData.java

[MERGE] main <- dev  병합

---

src/main/java/com/ll/playon/domain/party/party/dto/PartyDetailMemberDto.java

[FIX] 프로필이미지 NULL 처리

---

src/main/java/com/ll/playon/domain/chat/controller/ChatController.java
src/main/java/com/ll/playon/global/webSocket/config/WebSocketConfig.java
src/main/java/com/ll/playon/global/webSocket/security/JwtHandshakeInterceptor.java

<br/>
<br/>
<br/>
- 로그인 유저 대상으로 채팅 기능이 잘 작동하도록 웹소켓 Config 변경

[REFACTOR] 로그인 방식으로 WebConfig 리팩토링

---

src/main/java/com/ll/playon/domain/guild/guildBoard/controller/GuildBoardController.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/GuildBoardCommentDto.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/response/GuildBoardDetailResponse.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/response/GuildBoardSummaryResponse.java
src/main/java/com/ll/playon/domain/guild/guildBoard/service/GuildBoardService.java

* [FEAT] 게시글 생성/수정 시 presigned URL 반환 및 이미지 URL 저장 로직 추가
* [FIX] 길드게시판 게시글 수정 테스트코드 수정
* [REFACTOR] 길드가입요청 칭호추가
* [FIX] 길드 강제 퇴출 로직 수정
* [FIX] 이미 가입 되어있는 멤버 길드 가입 요청 안되도록 수정
* [REFACTOR] 길드가입, 길드정보 nickname->username으로 변경
* [REFACTOR] 사용자 이름 처리 로직 정리 (nickname 표기, username 초대 식별)
* [REFACTOR] 사용자 이름 처리 로직 정리(길드가입요청 nickname)
* [FIX] 길드게시판 이미지 업로드 presigned URL 적용 및 저장 로직 수정
* [FIX] 길드 가입 요청 후 승인시 길드멤버 테이블에 추가
* [FEAT] 길드게시판 작성자 boolean isAuthor 추가
<br/>
<br/>
<br/>

[FEAT] 길드게시판 작성자 boolean isAuthor 추가 (#181)

---

src/main/java/com/ll/playon/domain/guild/guildBoard/controller/GuildBoardController.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/GuildBoardCommentDto.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/response/GuildBoardDetailResponse.java
src/main/java/com/ll/playon/domain/guild/guildBoard/dto/response/GuildBoardSummaryResponse.java
src/main/java/com/ll/playon/domain/guild/guildBoard/service/GuildBoardService.java
src/main/java/com/ll/playon/domain/member/controller/MemberController.java
src/main/java/com/ll/playon/domain/member/service/MemberService.java
src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
src/main/java/com/ll/playon/domain/party/party/validation/PartyMemberValidation.java
src/main/java/com/ll/playon/domain/party/party/validation/PartyValidation.java
src/main/java/com/ll/playon/global/annotation/PartyPendingOnly.java
src/main/java/com/ll/playon/global/aspect/ActivePartyMemberCheckAspect.java
src/main/java/com/ll/playon/global/aspect/PartyInviterCheckAspect.java
src/main/java/com/ll/playon/global/aspect/PartyOwnerCheckAspect.java
src/main/java/com/ll/playon/global/aspect/PartyPendingCheckAspect.java
src/main/java/com/ll/playon/global/exceptions/ErrorCode.java
src/main/java/com/ll/playon/global/security/CustomAuthenticationFilter.java
src/main/java/com/ll/playon/global/security/SecurityConfig.java

[MERGE] main <- dev 병합

---

src/main/java/com/ll/playon/domain/board/controller/BoardCommentController.java
src/main/java/com/ll/playon/domain/board/controller/BoardController.java
src/main/java/com/ll/playon/domain/board/dto/response/GetBoardCommentResponse.java
src/main/java/com/ll/playon/domain/board/dto/response/GetBoardDetailResponse.java
src/main/java/com/ll/playon/domain/board/repository/BoardCommentRepository.java
src/main/java/com/ll/playon/domain/board/repository/BoardLikeRepository.java
src/main/java/com/ll/playon/domain/board/service/BoardCommentService.java
src/main/java/com/ll/playon/domain/board/service/BoardService.java

<br/>
<br/>
<br/>
- 자유게시판 게시글 상세 조회 응답 데이터 추가
- 작성자인지 확인
- 좋아요 눌렀는지 확인
- 자유게시판 댓글 목록 조회 응답 데이터 추가
- 작성자인지 확인

[FIX] 게시글/댓글 작성자 본인 확인, 좋아요확인

---

src/main/java/com/ll/playon/domain/guild/guildMember/repository/GuildMemberRepository.java
src/main/java/com/ll/playon/domain/guild/guildMember/service/GuildMemberService.java
src/main/java/com/ll/playon/domain/member/controller/MemberController.java
src/main/java/com/ll/playon/global/initData/BaseInitData.java
src/main/java/com/ll/playon/global/security/SecurityConfig.java

[FEAT] 가입한 길드 조회

---

src/main/java/com/ll/playon/domain/party/party/dto/response/GetCompletedPartyDto.java
src/main/java/com/ll/playon/domain/party/partyLog/dto/response/GetPartyLogResponse.java

<br/>
<br/>
<br/>
- 파티 결과창에서 이미지로 인한 `NPE` 발생 버그 해결

[FIX] 파티 결과창 NPE 해결

---

src/main/java/com/ll/playon/domain/member/dto/ProfileMemberDetailDto.java
src/main/java/com/ll/playon/domain/member/service/MemberService.java

<br/>
<br/>
<br/>
- 내 정보 응답 데이터에 `memberId` 추가

[REFACTOR] Me Response에 memberId 추가

---

src/main/java/com/ll/playon/domain/guild/guild/dto/response/GetGuildDetailResponse.java
src/main/java/com/ll/playon/domain/guild/guild/enums/GuildMemberRole.java
src/main/java/com/ll/playon/domain/guild/guild/service/GuildService.java
src/main/java/com/ll/playon/domain/guild/guildJoinRequest/repository/GuildJoinRequestRepository.java
src/test/java/com/ll/playon/domain/guild/guild/service/GuildServiceTest.java

<br/>
<br/>
<br/>
GuildMemberRole  도입
- 멤버가 아닐 경우
- 가입 신청자면 APPLICANT
- 아니면 GUEST 처리

[FEAT] 길드 상세 조회 myRole 처리 -가입신청자, 게스트 구분 추가

---

src/main/java/com/ll/playon/domain/notification/dto/response/NotificationResponse.java
src/main/java/com/ll/playon/domain/notification/repository/NotificationRepository.java
src/main/java/com/ll/playon/domain/notification/service/NotificationService.java
src/test/java/com/ll/playon/domain/notification/service/NotificationServiceTest.java
src/test/java/com/ll/playon/domain/notification/service/NotificationSseServiceTest.java

[REFATOR] 알림 로직 리팩토링
- 알림 조회 시 발신자ID -> 발신자 닉네임
- 알림 조회 시 읽지 않은 알림만 조회하게 수정

[REFATOR] 알림 로직 리팩토링

---

src/main/java/com/ll/playon/domain/guild/guild/service/GuildService.java
src/main/java/com/ll/playon/domain/guild/guildJoinRequest/repository/GuildJoinRequestRepository.java

[FEAT] 길드 상세 조회 myRole 처리 - 가입 거절 GUEST 처리

---

src/main/java/com/ll/playon/domain/guild/guild/service/GuildService.java
src/main/java/com/ll/playon/domain/guild/guildJoinRequest/repository/GuildJoinRequestRepository.java

[FEAT] 길드 상세 조회 myRole

---

src/main/java/com/ll/playon/domain/party/party/dto/request/GetAllPartiesRequest.java
src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
src/main/java/com/ll/playon/domain/party/party/service/PartyService.java

<br/>
<br/>
<br/>
- 기존 파티 리스트 검색 로직에서 필요없던 부분 제거 및 쿼리 개선
- 그에 따른 서비스 코드 리팩토링

[REFACTOR] 기존 파티 검색 쿼리 및 서비스 리팩토링

---

src/main/java/com/ll/playon/domain/party/party/dto/request/GetAllPartiesRequest.java

<br/>
<br/>
<br/>
- 파티 리스트 검색 시 파티 태그를 제대로 파싱하지 못하던 버그 수정

[FIX] 파티 태그 파싱 오류 수정

---

src/main/java/com/ll/playon/domain/game/game/controller/GameController.java

[REFACTOR] 게임 목록조회 페이징 수정

---

src/main/java/com/ll/playon/domain/guild/guildBoard/service/GuildBoardService.java
src/main/java/com/ll/playon/domain/member/controller/MemberController.java
src/main/java/com/ll/playon/domain/member/service/MemberService.java

<br/>
<br/>
<br/>
- 멤버
- 이미지 저장 DTO로 변경
- 이미지 테이블에 저장 추가
- 수정시 이미지 테이블 데이터 삭제하고 S3 삭제 추가
- 탈퇴시 이미지 삭제
- 길드 게시판
- 삭제시 이미지 삭제

[REFACTOR] 멤버, 길드 게시판 이미지 로직 수정

---

src/main/java/com/ll/playon/domain/chat/service/ChatMessageService.java

<br/>
<br/>
<br/>
- 브로드캐스트 시 /app 으로 보내지지 않는 버그 해결
- 트랜잭션이 반영되지 않던 버그 해결

[FIX] 브로드캐스트 트랜잭션 오류 해결

---

src/main/java/com/ll/playon/domain/guild/guildBoard/dto/response/GuildBoardDetailResponse.java
src/main/java/com/ll/playon/domain/guild/guildBoard/service/GuildBoardService.java

<br/>
<br/>
<br/>
- [FEAT] 길드게시판 상세 조회시 좋아요 여부 isLiked boolean값 추가

[FEAT] 길드게시판 상세 조회시 좋아요 여부 boolean값 추가

---

src/main/java/com/ll/playon/domain/game/game/controller/GameController.java
src/main/java/com/ll/playon/domain/guild/guild/dto/response/GetGuildListResponse.java
src/main/java/com/ll/playon/domain/member/service/MemberService.java

<br/>
<br/>
<br/>
- 길드 생성시 게임 미선택
- 정보 조회시 게임에 대한 정보가 없어 버그 발생

[REFACTOR] 길드 목록 조회시 게임 정보 버그 해결

---

src/main/java/com/ll/playon/domain/guild/guild/service/GuildService.java

<br/>
<br/>
<br/>
- 길드 수정시 게임 미선택

[REFACTOR] 길드 수정시 게임 미선택 버그 해결

---

src/main/java/com/ll/playon/domain/chat/entity/ChatMember.java
src/main/java/com/ll/playon/domain/chat/entity/PartyRoom.java
src/main/java/com/ll/playon/domain/game/game/entity/SteamGame.java
src/main/java/com/ll/playon/domain/game/game/entity/SteamGenre.java
src/main/java/com/ll/playon/domain/member/entity/Member.java
src/main/java/com/ll/playon/domain/member/entity/MemberSteamData.java
src/main/java/com/ll/playon/domain/party/party/entity/Party.java
src/main/java/com/ll/playon/domain/party/party/entity/PartyMember.java
src/main/java/com/ll/playon/domain/party/party/entity/PartyTag.java
src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
src/main/java/com/ll/playon/domain/party/partyLog/entity/PartyLog.java

<br/>
<br/>
<br/>
- 인덱스 설정 조건
- 복합 인덱스 사용을 극대화
- 중복 인덱스 사용을 최소화
- 인덱스 개수 최소화
- 가능한 한 가장 성능 좋게 최적화
- 조건에 맞도록 인덱스 수정
- 인덱스가 제대로 활용되도록 쿼리 내의 조건 순서 변경

[REFACTOR] 파티 관련 인덱스 최적화 및 성능 극대화

---

src/main/java/com/ll/playon/domain/guild/guild/dto/response/getGuildMemberResponse.java

<br/>
<br/>
<br/>
- 길드 상세페이지 멤버 조회
- 응답 데이터 닉네임 추가

[REFACTOR] 길드 멤버조회 응답 닉네임 추가

---

src/main/java/com/ll/playon/domain/board/controller/BoardController.java

<br/>
<br/>
<br/>
- 게시글 정렬 기본값 오타 수정

[FIX] 게시글 목록 정렬 오타 수정

---

src/main/java/com/ll/playon/global/security/CustomAuthenticationFilter.java

<br/>
<br/>
<br/>
- 로그인 유저 정보를 가져올 때 `NPE` 가 발생하던 버그 수정
- 기존의 허락된 경로는 인증을 하지 않아서 로그인 유저의 정보를 얻을 수 없었음
- 로그인 유저 정보를 얻어야 하는 경로는 얻도록 코드 수정
- 인증은 필요 없지만, 로그인 유저 정보가 필요한 경우 사용될 `URI` 리스트 생성

[FIX] 내 파티 및 파티 로그 조회 Actor NPE 문제 해결

---

src/main/java/com/ll/playon/domain/notification/dto/response/NotificationResponse.java
src/main/java/com/ll/playon/domain/notification/entity/Notification.java

[FIX] 리다이렉트 URL 어노테이션 수정

---

src/main/java/com/ll/playon/domain/notification/dto/response/NotificationResponse.java
src/main/java/com/ll/playon/domain/notification/dto/response/NotificationSummaryResponse.java
src/main/java/com/ll/playon/domain/notification/entity/Notification.java
src/main/java/com/ll/playon/domain/notification/service/NotificationService.java
src/test/java/com/ll/playon/domain/notification/service/NotificationServiceTest.java

[FIX] 발신자 닉네임 null 처리 수정

---

src/main/java/com/ll/playon/domain/notification/dto/response/NotificationSummaryResponse.java
src/main/java/com/ll/playon/domain/notification/service/NotificationService.java

[FIX] 알림 요약 조회 senderNickname 문제 수정

[FIX] 알림 요약 조회 senderNickname 문제 수정

---

src/main/java/com/ll/playon/domain/party/party/dto/response/GetCompletedPartyDto.java

<br/>
<br/>
<br/>
- 파티 결과 조회 응답값에 appId를 추가

[REFACTOR] 파티 결과 조회 응답값에 AppID 추가

---

src/main/java/com/ll/playon/global/webSocket/config/WebSocketConfig.java

<br/>
<br/>
<br/>
- WebSocektConfig 중복 코드 제거

[REFACTOR] 중복 코드 제거

---

src/main/java/com/ll/playon/domain/guild/guildJoinRequest/service/GuildJoinRequestService.java
src/main/java/com/ll/playon/domain/guild/util/GuildJoinRequestValidator.java

<br/>
<br/>
<br/>
- [REFACTOR] 길드 가입 Validator 분리

[REFACTOR] 길드 가입 Validator 분리

---

src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java

<br/>
<br/>
<br/>
- 파티 검색 시 기존 IN 대신 EXISTS를 활용하도록 변경
- 인덱스 활용을 극대화
- 유의미한 처리 속도 차이 확인
- 동일한 인덱스, 쿼리 개선 전
- 1.91s 소요시간 확인
- 동일한 인덱스, 쿼리 개선 후
- 444ms 소요시간 확인

[REFACTOR] 파티 검색 쿼리 최적화

---

src/main/java/com/ll/playon/domain/party/party/dto/response/GetCompletedPartyDto.java
src/main/java/com/ll/playon/domain/party/partyLog/dto/response/GetPartyLogResponse.java

<br/>
<br/>
<br/>
- ### 1. 파티 결과창 응답값 추가
- 파티 결과창 응답값에 `memberId` , `mvpMemberId` 추가

[REFACTOR] 파티 결과 응답 반환 응답값 추가

---

src/main/java/com/ll/playon/domain/guild/guildJoinRequest/service/GuildJoinRequestService.java
src/main/java/com/ll/playon/domain/guild/guildMember/service/GuildMemberService.java
src/main/java/com/ll/playon/domain/guild/util/GuildJoinRequestValidator.java

<br/>
<br/>
<br/>
- [REFACTOR] GuildMemberService 리팩토링

[REFACTOR] GuildMemberService 리팩토링

---

src/main/java/com/ll/playon/domain/game/game/entity/SteamGame.java
src/main/java/com/ll/playon/domain/party/party/entity/Party.java
src/main/java/com/ll/playon/domain/party/party/entity/PartyTag.java

<br/>
<br/>
<br/>
- `PartyRepository` 쿼리 하나하나 `EXPLAIN` 을 통해 인덱스 적용 확인
- 인덱스 성능을 극대화 시킬 수 있도록 인덱스 최적화

[REFACTOR] 인덱스 최적화

---

src/main/java/com/ll/playon/domain/party/party/dto/response/GetPartyDetailResponse.java

<br/>
<br/>
<br/>
- 파티 상세 응답 데이터에 `appId` 추가

[REFACTOR] 파티 상세 응답 데이터 추가

---

src/main/java/com/ll/playon/domain/game/batch/config/SteamGameBatchConfig.java
src/main/java/com/ll/playon/domain/game/batch/controller/BatchJobController.java
src/main/java/com/ll/playon/domain/game/batch/listener/SteamGameJobListener.java
src/main/java/com/ll/playon/domain/game/batch/processor/SteamGameProcessor.java
src/main/java/com/ll/playon/domain/game/batch/writer/SteamGameJpaItemWriter.java
src/main/java/com/ll/playon/domain/game/batch/writer/SteamGameWriterConfig.java
src/main/resources/application.yml
src/main/resources/logback-spring.xml

<br/>
<br/>
<br/>
- JobExecutionListener로 처리 건수 및 처리 시간 로깅 추가
- EntityManager clear() 처리로 영속성 컨텍스트 메모리 최적화 적용
- 처리 결과 및 성능 테스트 로그 확인

[REFACTOR] 배치 메모리 최적화 및 로그백 수정

---

Dockerfile

[FIX] Dockerfile, JVM 힙 메모리 명시적 설정

[FIX] Dockerfile, JVM 힙 메모리 명시적 설정

---

src/main/java/com/ll/playon/domain/party/party/dto/request/PutPartyRequest.java
src/main/java/com/ll/playon/domain/party/party/dto/response/GetPartyDetailResponse.java
src/main/java/com/ll/playon/domain/party/party/mapper/PartyMapper.java
src/main/java/com/ll/playon/domain/party/party/service/PartyService.java

<br/>
<br/>
<br/>
- 기존 `TODO` 주석 중 해결한 부분이나 불필요한 주석 제거

[REFACTOR] 불필요한 주석 제거

---

src/main/java/com/ll/playon/domain/board/repository/BoardCommentRepository.java
src/main/java/com/ll/playon/domain/board/repository/BoardRepository.java
src/main/java/com/ll/playon/domain/board/service/BoardService.java
src/main/java/com/ll/playon/domain/member/repository/MemberRepository.java

[FIX] 자유게시판 목록 프로필 이미지 버그 수정

---

src/main/java/com/ll/playon/domain/board/service/BoardService.java

[FIX] 게시글 조회수 업데이트 안 되는 버그 수정

---

src/main/java/com/ll/playon/domain/party/party/dto/response/GetPartyDetailResponse.java
src/main/java/com/ll/playon/domain/party/party/service/PartyService.java

<br/>
<br/>
<br/>
- 파티 상세 조회 시 응답값에 ownerId

[REFACTOR] 파티 상세 조회 Owner Id 추가

---

src/main/java/com/ll/playon/domain/game/game/repository/GameRepository.java

<br/>
<br/>
<br/>
- 게임 리스트 노출 시 ID 기준 오름차순으로 변경 (인기순)

[FIX] 게임 리스트 이상한 게임 상단부 노출 수정

---

src/main/java/com/ll/playon/domain/member/service/MemberService.java

<br/>
<br/>
<br/>
- 보유하고 있는 게임이 없다면 임의의 게임을 반환하던 로직을 제거 했습니다.

[FIX] 내 보유 게임 조회 수정

---

.github/workflows/deploy.yml

[REFACTOR] deploy 파일 수정
- 서버 기준 시간으로 설정
- 재시작 후 <none> 된 이미지 제거 명령어 추가

[REFACTOR] deploy 파일 수정

---

.github/workflows/deploy.yml
src/main/java/com/ll/playon/domain/member/service/MemberService.java

[REFACTOR] deploy.yml 파일 수정

---

Dockerfile

[REFACTOR] Dockerfile, timezone 명시

[REFACTOR] Dockerfile, timezone 명시

---

.github/workflows/deploy.yml
Dockerfile
src/main/java/com/ll/playon/domain/member/service/MemberService.java

[REFACTOR] Dockerfile, timezone 명시적으로 설정

[REFACTOR] Dockerfile, timezone 명시적으로 설정

---

.github/workflows/deploy.yml
Dockerfile
src/main/java/com/ll/playon/domain/member/service/MemberService.java
src/main/java/com/ll/playon/domain/party/party/entity/Party.java
src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java

<br/>
- 병합
<br/>
<br/>
- `dev` -> `main` 으로 병합

[MERGE] Main 병합

---

src/main/java/com/ll/playon/domain/member/service/MemberService.java
src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java

<br/>
- 병합
<br/>
<br/>
- `dev` -> `main` 병합

[MERGE] 메인 병합

---

src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
src/main/java/com/ll/playon/domain/party/party/service/PartyService.java

<br/>
<br/>
<br/>
- 메인용 최신 파티 로그 리스트 수정
- 기존 같은 사람의 로그는 1개만 가져오던 버그 수정

[FIX] 메인 파티 로그 리스트 수정

---

src/main/java/com/ll/playon/domain/member/service/MemberService.java
src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
src/main/java/com/ll/playon/domain/party/party/service/PartyService.java

<br/>
- 병합
<br/>
<br/>
- `dev` -> `main` 병합

[MERGE] 메인으로 병합
