prgrms-web-devcourse-final-project/WEB3_4_PlayON_BE

- .gitignore
- src/main/java/com/ll/playon/domain/member/MemberRepository.java
- src/main/java/com/ll/playon/domain/member/MemberService.java
- src/main/java/com/ll/playon/domain/member/MemberSteamDataRepository.java
- src/main/java/com/ll/playon/domain/member/entity/Gender.java
- src/main/java/com/ll/playon/domain/member/entity/Member.java
- src/main/java/com/ll/playon/domain/member/entity/MemberSteamData.java
- src/main/java/com/ll/playon/domain/member/entity/PlayStyle.java
- src/main/java/com/ll/playon/domain/member/entity/PreferredGenres.java
- src/main/java/com/ll/playon/global/initData/BaseInitData.java
- src/main/java/com/ll/playon/global/jpa/entity/BaseEntity.java
- src/main/java/com/ll/playon/global/jpa/entity/BaseTime.java
- src/main/java/com/ll/playon/global/security/UserContext.java
1. 사용자 member 엔티티 및 샘플 사용자 생성 
(스팀id : 123, username : sampleUser1)
(스팀id : 456, username : sampleUser2)
(스팀id : 789, username : sampleUser3)
2. 사용자 스팀 데이터 memberSteamData 엔티티 및 샘플 데이터 생성
(각 샘플 사용자에게 게임 3개 추가)
3. getActor()
현재 인증된 사용자를 반환하는 로직으로 현재는 id 가 1인 샘플 사용자1을 반환합니다!
다른 도메인에서 현재 인증된 사용자가 필요한 경우가 많아서 먼저 작업 했습니다!
이후 나머지 로직들이 완성되면 해당 메서드도 실제 로직으로 수정 예정입니다!
> [FEAT] 다른 도메인 작업을 위한 사용자 도메인 기초 작업

- src/main/java/com/ll/playon/domain/member/controller/MemberController.java
- src/main/java/com/ll/playon/domain/member/controller/SteamAuthController.java
- src/main/java/com/ll/playon/domain/member/controller/SteamRedirectPaths.java
- src/main/java/com/ll/playon/domain/member/dto/MemberAuthRequest.java
- src/main/java/com/ll/playon/domain/member/entity/Member.java
- src/main/java/com/ll/playon/domain/member/repository/MemberRepository.java
- src/main/java/com/ll/playon/domain/member/service/MemberService.java
- src/main/java/com/ll/playon/domain/member/service/SteamAuthService.java
- src/main/java/com/ll/playon/global/exceptions/ErrorCode.java
- src/main/java/com/ll/playon/global/initData/BaseInitData.java
- src/main/java/com/ll/playon/global/security/PasswordEncoderConfig.java
- src/test/java/com/ll/playon/domain/member/TestMemberHelper.java
- src/test/java/com/ll/playon/domain/member/controller/MemberControllerTest.java
- src/test/java/com/ll/playon/domain/member/controller/SteamAuthTest.java
이후 테스트 및 시연을 위해 스팀 계정이 아닌
일반적인 아이디와 비밀번호를 입력하는 회원가입과 로그인 방법을 구현하였습니다.
또한 일반 계정이 스팀 계정을 연동하는 API 도 구현하였습니다.
<br>
테스트시 인증 작업을 돕는 메서드를 만들었습니다.
~~~
ResultActions resultActions = testMemberHelper.requestWithUserAuth("noSteamMember", request);
~~~
와 같이 사용하면 해당 username 을 가진 사용자의
JWT 토큰값과 apikey 가 요청의 헤더에 부착되어 요청이 해당 사용자가 보낸 것으로 인증됩니다.
<br>
- 회원 정보 수정 ( 프론트에서 회원가입 두번째 단계로 사용됨)
- 회원 탈퇴
- 닉네임으로 회원 조회
> [FEAT] 스팀 없이 일반 회원 회원가입, 로그인, 스팀 연동

- src/main/java/com/ll/playon/domain/party/party/context/PartyContext.java
- src/main/java/com/ll/playon/domain/party/party/controller/PartyController.java
- src/main/java/com/ll/playon/domain/party/party/dto/PartyDetailMemberDto.java
- src/main/java/com/ll/playon/domain/party/party/dto/response/GetAllPendingMemberResponse.java
- src/main/java/com/ll/playon/domain/party/party/entity/Party.java
- src/main/java/com/ll/playon/domain/party/party/entity/PartyMember.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyMemberRepository.java
- src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
- src/main/java/com/ll/playon/domain/party/party/validation/PartyMemberValidation.java
- src/main/java/com/ll/playon/global/annotation/PartyOwnerOnly.java
- src/main/java/com/ll/playon/global/aspect/PartyOwnerCheckAspect.java
- src/main/java/com/ll/playon/global/exceptions/ErrorCode.java
- src/main/java/com/ll/playon/global/initData/BaseInitData.java
closes #27 
- 이미 파티장, 신청자, 파티원일 경우 각각 다르게 예외 처리
- 파티장만 참가 승인 가능
- 파티장만 참가 거절 가능
- 파티장만 참가 리스트 조회 가능
- 파티장 인가 체크 어노테이션 및 AOP 처리로 변경
- ThreadLocal 도입하여 각 요청 시의 Party 정보를 저장
---
- 파티장 인가 체크가 중복으로 많이 재사용됨
- 서비스 내의 코드를 최대한으로 줄이고 싶었음
- 해당 어노테이션이 쓰이는 파티 수정, 파티 참가 관련 작업들은 비동기 실행이 필요 없음
- `PartyContext` 컴포넌트 생성 후, `ThreadLocal<Party>` 생성하여 각 요청 시의 `Party` 정보 저장
- `AOP` 를 통해 해당 **partyId**의 `Party` 정보를 `Context` 에 저장
- 서비스 메서드 종료 후 `clear` 하여 호출 시마다 초기화하도록 설정
- 이후 비동기 작업 필요 시 `RequestScope` 빈을 등록하는 `Context` 추가 후 해당 메서드에 어노테이션으로 사용 예정
---
- 결론부터 말하자면 매우매우 미비
- 애초에 `AOP` 란 메서드 실행 **전/후/전후** 에 메서드를 한 번 더 호출하는 것에 불과
- `PartyContext` 에 저장 및 호출하는 것 또한 결국 `O(1)` 의 시간복잡도를 가짐
> [FEAT] 파티 신청 및 AOP 처리

- src/main/java/com/ll/playon/domain/member/controller/MemberController.java
- src/main/java/com/ll/playon/domain/member/dto/GameDetailDto.java
- src/main/java/com/ll/playon/domain/member/dto/GetMembersResponse.java
- src/main/java/com/ll/playon/domain/member/dto/MemberOwnedGamesDto.java
- src/main/java/com/ll/playon/domain/member/dto/MemberProfileResponse.java
- src/main/java/com/ll/playon/domain/member/dto/ProfileMemberDetailDto.java
- src/main/java/com/ll/playon/domain/member/repository/MemberRepository.java
- src/main/java/com/ll/playon/domain/member/repository/MemberSteamDataRepository.java
- src/main/java/com/ll/playon/domain/member/service/MemberService.java
- src/main/java/com/ll/playon/global/initData/BaseInitData.java
- src/test/java/com/ll/playon/domain/member/controller/MemberControllerTest.java
1. 사용자 상세 조회 : 마이페이지 관련 api. 사용자 정보와 소유한 게임 명단 응답
2. 닉네임으로 사용자 조회 : 같은 닉네임을 가진 사용자 명단 응답
<br>
1. OpenFeign 적용 및 사용자 도메인 가벼운 리펙토링 (정리)
2. 게임 도메인 작업
> [FEAT] 사용자 상세 조회 ( + 소유 게임), 닉네임으로 사용자 목록 조회

- build.gradle
- src/main/java/com/ll/playon/PlayOnApplication.java
- src/main/java/com/ll/playon/domain/game/game/repository/GenreRepository.java
- src/main/java/com/ll/playon/domain/member/dto/ProfileMemberDetailDto.java
- src/main/java/com/ll/playon/domain/member/entity/Member.java
- src/main/java/com/ll/playon/domain/member/service/MemberService.java
- src/main/java/com/ll/playon/domain/member/service/SteamAuthService.java
- src/main/java/com/ll/playon/global/app/AppConfig.java
- src/main/java/com/ll/playon/global/openFeign/SteamApiClient.java
- src/main/java/com/ll/playon/global/openFeign/SteamOpenIdClient.java
- src/main/java/com/ll/playon/global/openFeign/SteamStoreClient.java
- src/main/java/com/ll/playon/global/openFeign/dto/Game.java
- src/main/java/com/ll/playon/global/openFeign/dto/GameDetail.java
- src/main/java/com/ll/playon/global/openFeign/dto/GameDetailDeserializer.java
- src/main/java/com/ll/playon/global/openFeign/dto/GameDetailWrapper.java
- src/main/java/com/ll/playon/global/openFeign/dto/GameResponse.java
- src/main/java/com/ll/playon/global/openFeign/dto/Genre.java
- src/main/java/com/ll/playon/global/openFeign/dto/Player.java
- src/main/java/com/ll/playon/global/openFeign/dto/PlayerResponse.java
- src/main/java/com/ll/playon/global/openFeign/dto/SteamGameDetailResponse.java
- src/main/java/com/ll/playon/global/openFeign/dto/SteamGameResponse.java
- src/main/java/com/ll/playon/global/openFeign/dto/SteamResponse.java
- src/main/java/com/ll/playon/global/steamAPI/SteamAPI.java
- src/test/java/com/ll/playon/domain/member/controller/SteamAuthTest.java
1. RestTemplate 를 대체하여 OpenFeign 을 도입하였습니다.
2. 사용자가 소유한 게임을 통해 사용자의 선호 장르를 계산합니다.
> [FEAT] OpenFeign 도입 및 소유한 게임 리스트로 선호 장르 계산

- src/main/java/com/ll/playon/domain/party/party/controller/PartyController.java
- src/main/java/com/ll/playon/domain/party/party/dto/request/GetAllPartiesRequest.java
- src/main/java/com/ll/playon/domain/party/party/dto/response/GetPartyResponse.java
- src/main/java/com/ll/playon/domain/party/party/entity/Party.java
- src/main/java/com/ll/playon/domain/party/party/entity/PartyMember.java
- src/main/java/com/ll/playon/domain/party/party/entity/PartyTag.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
- src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
- src/main/java/com/ll/playon/domain/party/party/util/PartySortUtils.java
closes #32 
- 참여 가능한 파티 리스트 조회
- 검색 기능 1차 구현
- 추가 필요한 정보들은 다른 도메인 엔티티 작업 후 진행
- 쿼리 최적화 진행
- 다중 `JOIN` 사용 지양
- 필터링 결과의 `ID` 값을 우선적으로 추출
- 해당 `ID` 값을 사용하여 필요한 연관관계 정보들 따로 쿼리로 추출
- 해당 정보들 한 번에 합쳐서 `DTO` 로 변환 후 응답
- 검색에 필요한 인덱스 재설정
- 검색 성능 고려 및 인덱스 순서 고려
> [FEAT] 파티 리스트 조회 및 검색 기능 구현

- src/main/java/com/ll/playon/domain/image/entity/Image.java
- src/main/java/com/ll/playon/domain/image/mapper/ImageMapper.java
- src/main/java/com/ll/playon/domain/image/service/ImageService.java
- src/main/java/com/ll/playon/domain/member/controller/MemberController.java
- src/main/java/com/ll/playon/domain/member/service/MemberService.java
- src/main/java/com/ll/playon/domain/party/party/context/PartyMemberContext.java
- src/main/java/com/ll/playon/domain/party/party/controller/PartyController.java
- src/main/java/com/ll/playon/domain/party/party/dto/response/GetPartyMainResponse.java
- src/main/java/com/ll/playon/domain/party/party/entity/Party.java
- src/main/java/com/ll/playon/domain/party/party/entity/PartyMember.java
- src/main/java/com/ll/playon/domain/party/party/entity/PartyTag.java
- src/main/java/com/ll/playon/domain/party/party/mapper/PartyMemberMapper.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
- src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
- src/main/java/com/ll/playon/domain/party/party/type/PartyRole.java
- src/main/java/com/ll/playon/domain/party/party/validation/PartyMemberValidation.java
- src/main/java/com/ll/playon/domain/party/partyLog/PartyLogRepository.java
- src/main/java/com/ll/playon/domain/party/partyLog/controller/PartyLogController.java
- src/main/java/com/ll/playon/domain/party/partyLog/dto/request/PostPartyLogRequest.java
- src/main/java/com/ll/playon/domain/party/partyLog/dto/response/PostPartyLogResponse.java
- src/main/java/com/ll/playon/domain/party/partyLog/entity/PartyLog.java
- src/main/java/com/ll/playon/domain/party/partyLog/mapper/PartyLogMapper.java
- src/main/java/com/ll/playon/domain/party/partyLog/service/PartyLogService.java
- src/main/java/com/ll/playon/domain/party/partyLog/validation/PartyLogValidation.java
- src/main/java/com/ll/playon/global/annotation/ActivePartyMemberOnly.java
- src/main/java/com/ll/playon/global/aspect/ActivePartyMemberCheckAspect.java
- src/main/java/com/ll/playon/global/aws/s3/S3Service.java
- src/main/java/com/ll/playon/global/exceptions/ErrorCode.java
- src/main/java/com/ll/playon/global/security/UserContext.java
closes #43, #44 
- `PartyLog` 엔티티 추가 및 `Party` 엔티티에도 반영
- 로그 작성 구현
- 로그 작성 시 mvp 투표를 진행했으면, 이를 반영
- 로그 작성 시 이미지가 있으면
- `Postman` 을 통한 1차 테스트 완료
- `@ActivePartyMemberOnly` 어노테이션 추가
- `PartyMemberContext` 추가 개설 및 `ThreadLocal` 사용
- `AOP` 를 사용해서 해당 어노테이션으로 해당 파티의 파티원인지 인가 진행
- `PENDING` 상태의 파티원이어도 비허용
- 중복 코드 리팩토링
- 파티 로그 이미지 업로드 및 경로를 로컬 DB에 저장
- `Party` 관련 테이블들 이름 수정
- 복수형 -> 단수형
- `Image.Builder` 수정
- `ImageType` 추가 반영
- 단일 이미지 저장 로직 분리
- `Party` 엔티티의 상속 취소 및 해당 필드들 개별로 추가
- 기존 `createdAt` 필드에 `Null` 이 들어가던 문제 해결
> [FEAT] PartyLog 엔티티 개설 및 파티 로그 작성

- build.gradle
- src/main/java/com/ll/playon/domain/image/entity/Image.java
- src/main/java/com/ll/playon/domain/image/repository/ImageRepository.java
- src/main/java/com/ll/playon/domain/image/service/ImageService.java
- src/main/java/com/ll/playon/domain/party/party/validation/PartyMemberValidation.java
- src/main/java/com/ll/playon/domain/party/partyLog/controller/PartyLogController.java
- src/main/java/com/ll/playon/domain/party/partyLog/dto/request/PutPartyLogRequest.java
- src/main/java/com/ll/playon/domain/party/partyLog/dto/response/PartyLogResponse.java
- src/main/java/com/ll/playon/domain/party/partyLog/entity/PartyLog.java
- src/main/java/com/ll/playon/domain/party/partyLog/event/ImageDeleteEvent.java
- src/main/java/com/ll/playon/domain/party/partyLog/listener/ImageEventListener.java
- src/main/java/com/ll/playon/domain/party/partyLog/repository/PartyLogRepository.java
- src/main/java/com/ll/playon/domain/party/partyLog/service/PartyLogService.java
- src/main/java/com/ll/playon/global/aspect/EventExceptionLoggingAspect.java
- src/main/java/com/ll/playon/global/aws/s3/S3Service.java
- src/main/java/com/ll/playon/global/exceptions/ErrorCode.java
- src/main/java/com/ll/playon/global/exceptions/EventListenerException.java
- src/main/java/com/ll/playon/standard/util/LogUtil.java
- 파티 로그 수정 기능 구현
- `Postman` 으로 1차 테스트 완료
- 기존 이미지 삭제 시
- `S3` 에서 이미지 삭제
- **로컬 DB**에서 **조회용 URL** 삭제
- 새로운 이미지 추가 시
- `S3` 에 이미지 추가
- **로컬 DB**에 **조회용 URL** 추가
- 파티 로그 삭제 기능 구현
- `Postman` 으로 1차 테스트 완료
- `S3` 에서 이미지 삭제
- **로컬 DB**에서 **조회용 URL** 삭제
- `S3` 단일 이미지 처리 추가
- **로컬 DB** 단일 이미지 처리 추가
- 단일 이미지 추가에 따른 `Image` 인덱스 재설정
- 파티 로그 삭제에 이벤트 리스너 도입
- 이벤트 리스너 도입에 따른 AOP 추가
- `@Transactional` 은 __DB 작업__을 원자적으로 수행하기 위한 것
- `S3` 나 `Redis` 같은 외부 시스템에서의 작업까지 자동으로 **롤백** 및 **커밋**을 해주지는 않음
- 즉, `S3` 와 `DB` 는 완전히 같은 트랜잭션에 있다고 보기는 어려움
> #### 이전처럼 같은 `@Transactional` 안에 처리하는 것으로 삭제 처리를 끝냈을 경우
- `S3` 삭제가 실패하면 예외 발생
- __로컬 DB__ 트랜잭션 롤백
- `S3` 삭제 실패로 인해서 `DB` 삭제도 불가능해짐
> #### 이벤트 리스너의 `@TransactionalEventListner(phase = TransactionPhase.AFTER_COMMIT)` 을 사용하면
- `S3` 삭제에 실패하더라도, 이미 __로컬 DB__ 커밋은 완료된 상태이기 …
> [FEAT] 파티 로그 수정 및 삭제 구현

- src/main/java/com/ll/playon/domain/game/game/controller/GameController.java
- src/main/java/com/ll/playon/domain/game/game/dto/request/GameSearchCondition.java
- src/main/java/com/ll/playon/domain/game/game/dto/response/GameAutoCompleteResponse.java
- src/main/java/com/ll/playon/domain/game/game/dto/response/GameDetailResponse.java
- src/main/java/com/ll/playon/domain/game/game/dto/response/GameDetailWithPartyResponse.java
- src/main/java/com/ll/playon/domain/game/game/dto/response/GameSummaryResponse.java
- src/main/java/com/ll/playon/domain/game/game/dto/response/PartyLogSummaryResponse.java
- src/main/java/com/ll/playon/domain/game/game/dto/response/PartySummaryResponse.java
- src/main/java/com/ll/playon/domain/game/game/enums/PlayerType.java
- src/main/java/com/ll/playon/domain/game/game/enums/ReleaseStatus.java
- src/main/java/com/ll/playon/domain/game/game/repository/GameRepository.java
- src/main/java/com/ll/playon/domain/game/game/repository/GameRepositoryCustom.java
- src/main/java/com/ll/playon/domain/game/game/repository/GameRepositoryImpl.java
- src/main/java/com/ll/playon/domain/game/game/service/GameService.java
- src/main/java/com/ll/playon/domain/party/party/entity/PartyMember.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
- src/main/java/com/ll/playon/domain/party/partyLog/repository/PartyLogRepository.java
- src/main/java/com/ll/playon/global/config/WebConfig.java
- src/test/java/com/ll/playon/domain/game/controller/GameControllerTest.java
🎮 게임 상세 기능 구현
1. 게임 검색 및 조회
게임명 키워드 기반 자동완성 검색 기능 구현
2. 게임 상세 정보 조회
/api/games/{appid}/details API 구현
단일 게임에 대한 상세 정보 (설명, 지원 플랫폼, 개발사 등) 응답
함께 해당 게임에 대한 파티 목록과 파티 로그도 함께 포함하여 반환
3. 게임별 파티 목록 조회
/api/games/{appid}/party API 추가
해당 게임의 파티 목록을 페이징 처리하여 반환
4. 게임별 파티 로그 조회
/api/games/{appid}/logs API 추가
해당 게임의 파티 로그를 페이징 처리하여 반환
✅ 테스트 코드
위 기능 모두에 대한 단위 테스트 작성 완료
> [FEAT] 게임 상세 기능 구현

- src/main/java/com/ll/playon/domain/game/game/service/GameService.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
- src/main/java/com/ll/playon/domain/party/partyLog/repository/PartyLogRepository.java
- src/test/java/com/ll/playon/domain/game/controller/GameControllerTest.java
1. 게임 상세 조회 오류 수정
- 기존 JPQL 쿼리에서 p.game = :gameId로 잘못된 타입(Long ↔ SteamGame) 매칭으로 인해 InvalidDataAccessApiUsageException 발생
- @Query 제거 후, Spring Data JPA 메서드 네이밍 기반으로 findByGame(SteamGame game, Pageable pageable) 메서드 사용
2. 게임별 파티 목록 조회 기능 수정
- findByGameId(Long gameId, Pageable pageable) → findByGame(SteamGame game, Pageable pageable) 로 수정
- Service에서 SteamGame 조회 후 전달하는 구조로 통일
3. 게임별 파티 로그 조회 기능 수정
- PartyLog 조회 시도 시 발생한 Entity 타입 미스매칭 해결
- 동일하게 SteamGame 엔티티 객체를 기준으로 Repository 메서드 재정의 및 호출 방식 수정
> [FIX] GameControllerTest 오류 수정

- src/main/java/com/ll/playon/domain/game/game/entity/SteamGame.java
- src/main/java/com/ll/playon/domain/notification/entity/Notification.java
- src/main/java/com/ll/playon/domain/notification/repository/NotificationRepository.java
- src/main/java/com/ll/playon/domain/notification/service/NotificationService.java
- src/main/resources/application-dev.yml
- [FIX] RDS 연동 중 테이블 생성 시 발생하는 에러 수정
1. Notification.java 엔티티에서 read -> isRead로 수정
2. SteamGame.java 엔티티에서 잘못된 인덱스 제거
"@Index(name = "idx_game_genre", columnList = "id, genre_name")"
3. application-dev.yml 에서MySQLDialect 수정
> [FIX] RDS 연동 중 테이블 생성 시 발생하는 에러 수정

- src/main/java/com/ll/playon/domain/guild/guild/controller/GuildController.java
- src/main/java/com/ll/playon/domain/guild/guild/dto/request/PostGuildRequest.java
- src/main/java/com/ll/playon/domain/guild/guild/dto/request/PutGuildRequest.java
- src/main/java/com/ll/playon/domain/guild/guild/entity/Guild.java
- src/main/java/com/ll/playon/domain/guild/guild/service/GuildService.java
- src/main/java/com/ll/playon/domain/image/repository/ImageRepository.java
- src/main/java/com/ll/playon/domain/image/service/ImageService.java
- src/main/java/com/ll/playon/global/exceptions/ErrorCode.java
- src/main/java/com/ll/playon/global/initData/BaseInitData.java
- src/main/java/com/ll/playon/global/validation/FileValidator.java
- Presigned URL을 이용한 길드 대표 이미지 업로드 기능 구현
- 길드 생성 시 이미지 URL을 함께 전달받아 DB(image 테이블)에 저장
- 이미지를 저장하지 않는다면 조회시 프론트에서 기본 이미지 제공
- 길드 수정 시 이미지 변경 여부를 비교하여 기존 이미지 삭제 + 새 이미지 저장
- 길드 삭제 시
- 연관 태그 및 멤버 제거
- 이미지 URL 기준으로 S3 및 DB에서 삭제 처리(실제 S3 연결시 주석 해제 예정)
- 길드 정보 마스킹(soft delete)
#82
> [FEAT] 길드 이미지 업로드

- src/main/java/com/ll/playon/domain/game/game/projection/TopPartyGameProjection.java
- src/main/java/com/ll/playon/domain/game/game/projection/TopPlaytimeGameProjection.java
- src/main/java/com/ll/playon/domain/game/game/repository/LongPlaytimeGameRepository.java
- src/main/java/com/ll/playon/domain/game/game/repository/WeeklyGameRepository.java
- src/main/java/com/ll/playon/domain/game/game/scheduler/GameScheduler.java
- src/main/java/com/ll/playon/domain/game/game/service/GameService.java
- src/main/java/com/ll/playon/domain/guild/guild/controller/GuildController.java
- src/main/java/com/ll/playon/domain/guild/guild/entity/WeeklyPopularGuild.java
- src/main/java/com/ll/playon/domain/guild/guild/projection/TopGuildPostProjection.java
- src/main/java/com/ll/playon/domain/guild/guild/repository/GuildRepositoryImpl.java
- src/main/java/com/ll/playon/domain/guild/guild/repository/WeeklyPopularGuildRepository.java
- src/main/java/com/ll/playon/domain/guild/guild/scheduler/GuildScheduler.java
- src/main/java/com/ll/playon/domain/guild/guild/service/GuildService.java
- src/main/java/com/ll/playon/domain/guild/guildBoard/repository/GuildBoardRepository.java
- src/main/java/com/ll/playon/domain/member/service/MemberService.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
- src/main/java/com/ll/playon/global/initData/BaseInitData.java
- GuildScheduler를 통한 주간 인기 길드 집계 스케줄러 추가
- 월요일 새벽 3시 진행
- 주간 인기 길드 통계 테이블 (`weekly_popular_guild`) 생성
- 게시글 수 기반 활동 정렬 (`sort=activity`) 기능 추가
- QueryDSL에서 Guild → GuildBoard 연관관계 기반 정렬 처리
> [FEAT] 길드 인기 정렬 및 주간 활동량 기반 추천 기능 구현

- src/main/java/com/ll/playon/domain/chat/controller/ChatController.java
- src/main/java/com/ll/playon/domain/chat/dto/ChatMessageDto.java
- src/main/java/com/ll/playon/domain/chat/entity/ChatMember.java
- src/main/java/com/ll/playon/domain/chat/entity/PartyRoom.java
- src/main/java/com/ll/playon/domain/chat/event/ChatRoomDetectedAfterGameStartedEvent.java
- src/main/java/com/ll/playon/domain/chat/listener/PartyRoomEventListener.java
- src/main/java/com/ll/playon/domain/chat/repository/ChatMemberRepository.java
- src/main/java/com/ll/playon/domain/chat/scheduled/DeletePartyRoomsScheduler.java
- src/main/java/com/ll/playon/domain/image/event/ImageDeleteEvent.java
- src/main/java/com/ll/playon/domain/image/listener/ImageEventListener.java
- src/main/java/com/ll/playon/domain/image/repository/ImageRepository.java
- src/main/java/com/ll/playon/domain/image/service/ImageService.java
- src/main/java/com/ll/playon/domain/party/party/controller/PartyController.java
- src/main/java/com/ll/playon/domain/party/party/entity/Party.java
- src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
- src/main/java/com/ll/playon/domain/party/partyLog/controller/PartyLogController.java
- src/main/java/com/ll/playon/domain/party/partyLog/service/PartyLogService.java
- src/main/java/com/ll/playon/global/initData/BaseInitData.java
- src/main/java/com/ll/playon/global/security/SecurityConfig.java
- src/main/java/com/ll/playon/global/security/UserContext.java
- src/main/java/com/ll/playon/global/webSocket/config/WebSocketConfig.java
- src/main/java/com/ll/playon/global/webSocket/security/JwtHandshakeInterceptor.java
- src/main/resources/logback-spring.xml
<br/>
<br/>
- `Postman` 을 통한 `API` 호출 테스트 진행
<br/>
- `Party` , `PartyRoom` , `PartyLog` 컨트롤러 사용자 인증 방식 변경
- `JWT` 및 쿠키를 활용하여 유저 정보를 가져오도록 변경
- UserContext에서 멤버 조회를 한 번에 가져오는 `getActualActor` 메서드 추가
- 위의 컨트롤러에서 해당 방식으로 유저 정보 획득
- 인덱스 추가 및 변경이 필요한 엔티티 변경
- 이벤트 이름은 이름으로 어떤 이벤트를 진행할 지 유추할 수 없도록 하라는 강사님의 피드백
- 기존에는 `PartyRoomsDeleteEvent` 이름으로 이벤트를 등록
- 사실만 나타내고 리스너에서 처리하도록 `ChatRoomDetectedAfterGameStartedEvent` 로 클래스명 변경
- `countByPartyRoomIds` 쿼리에서 바인딩 문제 발견
- 파라미터명에 맞추어서 해당 부분 수정
- 기존에는 파티 리스트 조회 시 검색 조건과 상관없이 내 파티를 페이지 최상단에 노출
- 정책 재확인, 정책에 따라 코드 변경
- 파티 리스트 조회 시 검색 조건에 맞는 파티 리스트들을 출력하며, 내 파티는 아예 제외
- `JWT` 를 이용해서 채팅방에 입장이 가능한지 테스트
- 입장까지는 테스트 완료
- 아직 프론트와 제대로 연동되지 않았기 때문에, 추후 테스트 반드시 필요
- `JwtHandshakeInterceptor` 에서 `Jwt` 를 기반으로 유저 정보를 가져올 때, `userId` 를 제대로 가져오지 못함
- 타입 변환 오류 발생
- 기존 …
> [REFACTOR] 파티 관련 기능 리팩토링 및 이미지 수정

- src/main/java/com/ll/playon/domain/party/party/dto/PartyDetailMemberDto.java
- src/main/java/com/ll/playon/domain/party/party/dto/PartyMemberIdProfileImgDto.java
- src/main/java/com/ll/playon/domain/party/party/dto/response/GetPartyDetailResponse.java
- src/main/java/com/ll/playon/domain/party/party/dto/response/GetPartyResponse.java
- src/main/java/com/ll/playon/domain/party/party/entity/Party.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
- src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
- src/main/java/com/ll/playon/domain/party/party/type/PartyRole.java
- src/main/java/com/ll/playon/domain/party/party/util/PartySortUtils.java
- src/main/java/com/ll/playon/domain/party/partyLog/service/PartyLogService.java
- src/main/java/com/ll/playon/domain/title/dto/RepresentativeTitleDto.java
- src/main/java/com/ll/playon/domain/title/repository/MemberTitleRepository.java
- src/main/java/com/ll/playon/domain/title/service/MemberTitleService.java
<br/>
<br/>
<br/>
- 기존 정렬 및 페이징이 제대로 안 되던 버그 발견
- 검색 및 페이징이 되도록 버그 수정
- 이제 정렬 기준이나 값들에 따라 올바른 필터링 가능
- 검색 속도가 좀 느린듯하여, 성능 개선 시급해보임
- 프론트 측 요구에 맞춰 응답 데이터 변경
- 기존은 `Pending` 하나로 대기자를 구분
- 초대받은 사람과 신청한 사람을 추가로 나누기 위해 `Enum` 값 추가
- `INVITER("초대자")`
- `N+1` 방지를 위해 대표 칭호 조회하는 쿼리 및 코드를 추가
> [FIX] 파티 전체 조회 필터링 버그 수정 및 응답 값들 변경

- src/main/java/com/ll/playon/domain/member/controller/MemberController.java
- src/main/java/com/ll/playon/domain/member/service/MemberService.java
- src/main/java/com/ll/playon/domain/party/party/entity/Party.java
- src/main/java/com/ll/playon/domain/party/party/entity/PartyMember.java
- src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
- src/main/java/com/ll/playon/global/annotation/PartyInviterOnly.java
- src/main/java/com/ll/playon/global/aspect/PartyInviterCheckAspect.java
- src/main/java/com/ll/playon/global/exceptions/ErrorCode.java
<br/>
<br/>
<br/>
- `Inviter` 타입을 추가하여 초대 받은 사람을 구분
- 파티 초대 승인 기능 추가
- 파티 초대 거절 기능 추가
- `PartyInviterOnly` 어노테이션 추가
- 위를 활용한 `AOP` 를 추가하여, 파티 초대 대상에 한한 인가 진행
- 서비스 코드 2~3줄로 끝나는 마법
- 기존에는  `Setter` 를 이용해 필드 업데이트 진행
- 외부에서의 `Set` 이 좋지 않다고 판단하여, 관련된 엔티티 클래스 내부 메서드들 생성
- 해당 내부 메서드를 사용하여 __참조 객체__를 대상으로 업데이트 진행
- `Setter` 사용 부분이 발견되면 나머지도 변경 예정
> [FEAT] 파티 초대 승인/거절 및 AOP 추가

- build.gradle
- src/main/java/com/ll/playon/PlayOnApplication.java
- src/main/java/com/ll/playon/domain/chat/controller/ChatController.java
- src/main/java/com/ll/playon/domain/member/controller/MemberController.java
- src/main/java/com/ll/playon/domain/member/service/MemberService.java
- src/main/java/com/ll/playon/domain/member/service/SignupEvent.java
- src/main/java/com/ll/playon/domain/member/service/SignupEventListener.java
- src/main/java/com/ll/playon/domain/member/service/SteamAsyncService.java
- src/main/java/com/ll/playon/global/exceptions/ErrorCode.java
- src/main/java/com/ll/playon/global/initData/BaseInitData.java
- src/main/java/com/ll/playon/global/openFeign/SteamApiClient.java
- src/main/java/com/ll/playon/global/security/UserContext.java
- src/main/java/com/ll/playon/global/steamAPI/SteamAPI.java
- src/main/resources/application.yml
- src/test/java/com/ll/playon/domain/member/controller/SteamAuthAsyncTest.java
- src/test/java/com/ll/playon/domain/member/controller/SteamAuthTest.java
1. 소유 게임 조회 로직 비동기로 전환
2. Resilience4j 라이브러리 사용해서 retry, rateLimiter, circuitBreaker 도입
---
1. 하루 최대 100,000번
2. 5분에 200개? (정확하지는 않음)
> [FEAT] 스팀 API 장애 대응

- src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
- src/main/java/com/ll/playon/domain/party/party/util/PartySortUtils.java
<br/>
<br/>
<br/>
- 기존 인원수 정렬 필터링을 이상하게 복잡하게 진행하고 있었음
- `Party` 엔티티의 `total` 필드를 기준으로 정렬하도록 변경
- 그로 인한 코드량 대폭 감소
> [REFACTOR] 파티 리스트 조회 리팩토링

- src/main/java/com/ll/playon/global/webSocket/config/WebSocketConfig.java
- src/main/java/com/ll/playon/global/webSocket/security/CustomHandshakeHandler.java
- src/main/java/com/ll/playon/global/webSocket/security/JwtHandshakeInterceptor.java
<br/>
<br/>
<br/>
- 채팅방에서 `Principa` l이 `null` 로 들어오는 문제 발생
- `DfeaultHandshakeHandler` 를 `WebSocketConfig` 에 추가
- 이전의 `Principal` 정보를 가져올 수 있도록 수정
- `JwtHandshakeInterceptor` 에서 쿠키 뿐만 아니라 `JWT` 값으로도 연동이 가능하도록 설정
> [FIX] 채팅방 Principal NPE 해결

- src/main/java/com/ll/playon/domain/member/controller/MemberController.java
- src/main/java/com/ll/playon/domain/member/service/MemberService.java
- src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
- src/main/java/com/ll/playon/domain/party/party/validation/PartyMemberValidation.java
- src/main/java/com/ll/playon/domain/party/party/validation/PartyValidation.java
- src/main/java/com/ll/playon/global/annotation/PartyPendingOnly.java
- src/main/java/com/ll/playon/global/aspect/ActivePartyMemberCheckAspect.java
- src/main/java/com/ll/playon/global/aspect/PartyInviterCheckAspect.java
- src/main/java/com/ll/playon/global/aspect/PartyOwnerCheckAspect.java
- src/main/java/com/ll/playon/global/aspect/PartyPendingCheckAspect.java
- src/main/java/com/ll/playon/global/exceptions/ErrorCode.java
<br/>
<br/>
<br/>
- 파티 신청 취소 기능 구현
- 파티 신청자용  `Annotation` 및 `AOP` 추가
- 파티 신청자인지 인가 체크 진행
- `PENDING` 상태인 파티에서만 초대/참여 및 승인 가능
- 거절은 따로 제한 두지 않음
- 모든 유저가 파티 신청자 목록을 볼 수 있도록 변경
- 파티 초대/참여 및 승인 시 파티의 정원이 넘지 않도록 제한
- 어울리지 않는 메서드명 일부 변경
> [FEAT] 파티 신청 취소

- src/main/java/com/ll/playon/domain/member/controller/MemberController.java
- src/main/java/com/ll/playon/domain/member/service/MemberService.java
- src/main/java/com/ll/playon/domain/party/party/controller/PartyController.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyMemberRepository.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
- src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
- src/main/java/com/ll/playon/domain/party/party/util/PartyMergeUtils.java
- src/main/java/com/ll/playon/domain/party/partyLog/util/PartyLogUtils.java
- src/main/java/com/ll/playon/global/initData/BaseInitData.java
<br/>
<br/>
<br/>
- 마이 페이지에서 내가 참여 중인 파티 조회 기능 구현
- `List` 로 감싸서 반환
- 마이 페이지에서 내가 파티 로그를 작성한 적 있는 종료된 파티들을 최근에 끝난 순으로 조회
- 페이징 처리
- 타 유저 페이지에서 유저가 참여 중인 파티 조회 기능 구현
- `List` 로 감싸서 반환
- 타 유저 페이지에서 타 유저가 파티 로그를 작성한 적 있는 종료된 파티들을 최근에 끝난 순으로 조회
- 페이징 처리
- 기존 잘못된 필터링이 들어가던 버그 픽스
- 기존 `mergePartyWithJoinDto` 가 이번 추가되는 기능들에도 사용됨
- `PartyMergeUtils` 로 분류 후 `static` 메서드로 지정
- `BaseInit` 에 `PartyLog` 가 일부 생성되도록 추가
- 좀 더 직관적이게 이름을 재정의
> [FEAT] 유저 및 내 파티 조회 및 로그가 작성된 파티 조회

- src/main/java/com/ll/playon/domain/party/party/entity/Party.java
- src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
<br/>
<br/>
<br/>
- 파티 상세 조회 시 신청자, 초대자는 나오지 않도록 수정
- 인원이 마감된 파티는 노출되지 않도록 변경
> [REFACTOR] 정책에 따른 파티 조회 가능 여부 변경

- src/main/java/com/ll/playon/domain/chat/service/ChatService.java
- src/main/java/com/ll/playon/domain/party/party/dto/PartyDetailMemberDto.java
- src/main/java/com/ll/playon/domain/party/party/dto/response/GetCompletedPartyDto.java
- src/main/java/com/ll/playon/domain/party/party/entity/Party.java
<br/>
<br/>
<br/>
- 파티 종료 시 종료 시간을 반영하지 않던 버그 수정
- 정상적으로 파티가 종료되면 종료 시간 반영
- 1번의 버그로 인해 `Party` 엔티티의 `endedAt` 이 `Null` 로 유지
- 이로 인한 `NPE` 발생
- 1번을 해결해줌으로 `NPE` 해결
- `MVP` 포인트도 같이 응답하도록 추가
> [FIX] 파티 결과창 조회 버그 수정 및 MVP 포인트 응답에 추가

- src/main/java/com/ll/playon/domain/chat/controller/ChatController.java
- src/main/java/com/ll/playon/domain/party/party/controller/PartyController.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
- src/main/java/com/ll/playon/domain/party/partyLog/controller/PartyLogController.java
<br/>
<br/>
<br/>
- 인원이 가득 찬 파티 리스트는 노출시키지 않도록 수정
- `TODO` 로 주석처리한 코드상 불필요한 부분 삭제
> [REFACTOR] 파티 리스트 조회 시 인원이 가득 찬 파티는 리스트에 비노출

- src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
- src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
<br/>
<br/>
<br/>
- 메인 파티 리스트 조회 시 `limit` 만큼의 개수를 원할하게 가져오지 못하는 버그 수정
> [FIX] 파티 메인에서 limit 만큼의 페이지를 가져오지 못하는 버그 수정

- src/main/java/com/ll/playon/domain/party/party/controller/PartyController.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
- src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
- src/main/java/com/ll/playon/global/security/CustomAuthenticationFilter.java
<br/>
<br/>
<br/>
- `isMacSupported` 검색 조건 추가
- defaultValue` 는 `false` 이고, 이 때는 이 조건과 상관 없이 전체 리스트 조회
- `true` 이면 `SteamGame` 의 `IsMacSupported` 가 `true` 인 것 만 조회
> [FEAT] 파티 리스트 조회 맥 조건 추가

- src/main/java/com/ll/playon/domain/game/game/repository/GameRepository.java
- src/main/java/com/ll/playon/domain/party/party/controller/PartyController.java
- src/main/java/com/ll/playon/domain/party/party/dto/request/GetAllPartiesRequest.java
- src/main/java/com/ll/playon/domain/party/party/dto/request/PostPartyRequest.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
- src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
- src/main/java/com/ll/playon/global/initData/BaseInitData.java
- src/test/java/com/ll/playon/domain/game/controller/GameControllerTest.java
<br/>
<br/>
<br/>
- 기존에는 `SteamGame` 의 기본 키 `id` 를 사용
- 파티 생성 및 파티 리스트 조회에서 `SteamGame` 의 `appId` 를 사용하도록 변경
> [FIX] 파티 생성 및 리스트 조회 시 appId 사용

- src/main/java/com/ll/playon/domain/chat/context/ChatMemberContext.java
- src/main/java/com/ll/playon/domain/chat/context/PartyRoomContext.java
- src/main/java/com/ll/playon/domain/chat/controller/ChatMessageController.java
- src/main/java/com/ll/playon/domain/chat/dto/ChatMemberDto.java
- src/main/java/com/ll/playon/domain/chat/dto/ChatMessageDto.java
- src/main/java/com/ll/playon/domain/chat/service/ChatMessageService.java
- src/main/java/com/ll/playon/domain/chat/service/ChatService.java
- src/main/java/com/ll/playon/domain/party/party/type/PartyRole.java
- src/main/java/com/ll/playon/global/annotation/ChatMemberOnly.java
- src/main/java/com/ll/playon/global/aspect/ChatMemberCheckAspect.java
- src/main/java/com/ll/playon/global/aspect/PartyInviterCheckAspect.java
- src/main/java/com/ll/playon/global/aspect/PartyOwnerCheckAspect.java
- src/main/java/com/ll/playon/global/aspect/PartyPendingCheckAspect.java
- src/main/java/com/ll/playon/global/exceptions/ErrorCode.java
- src/main/java/com/ll/playon/global/webSocket/config/WebSocketConfig.java
<br/>
<br/>
<br/>
- 이미 채팅방 입장 시 별다른 조치 없이 바로 입장 처리
- 채팅 멤버용 어노테이션 추가
- 채팅 멤버 인가 `AOP` 적용
- `PartyRoomContext` 및 `ChatMemberContext` 추가
- 메시지는 `ChatMember` 만 전송할 수 있도록 설정
- 퇴장은 `ChatMember` 만 가능하도록 변경
- 사용하지 않는 엔드포인트 메서드 정리
- 기존 `Owner` 와 `Member` 인지를 묶어서 확인할 수 있는 메서드 추가
- 추후 사용할 수도 있으니, 반대를 묶어서 확인할 수 있는 메서드도 추가
- 채팅 멤버의 이미지 호출 시 `NPE` 가 발생하지 않도록 수정
- 기존 코드 일부 리팩토링 진행
> [FIX] 채팅 정책 반영 및 인가 AOP 진행

- src/main/java/com/ll/playon/domain/chat/listener/PartyRoomEventListener.java
- src/main/java/com/ll/playon/domain/chat/policy/PartyRoomPolicy.java
- src/main/java/com/ll/playon/domain/chat/repository/ChatMemberRepository.java
- src/main/java/com/ll/playon/domain/chat/scheduler/PartyRoomsScheduler.java
- src/main/java/com/ll/playon/domain/member/service/MemberService.java
- src/main/java/com/ll/playon/domain/party/party/entity/Party.java
- src/main/java/com/ll/playon/domain/party/party/entity/PartyMember.java
- src/main/java/com/ll/playon/domain/party/party/entity/PartyTag.java
- src/main/java/com/ll/playon/domain/party/party/event/ExpiredPartyDetectedEvent.java
- src/main/java/com/ll/playon/domain/party/party/listener/PartyEventListener.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyMemberRepository.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
- src/main/java/com/ll/playon/domain/party/party/scheduler/PartyScheduler.java
- src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
- src/main/java/com/ll/playon/global/exceptions/ErrorCode.java
<br/>
<br/>
<br/>
- 파티를 삭제(Hard Delete)하기 위한 메서드 추가
- 관련된 모든 연관관계를 끊어주는 메서드 추가
- 파티 삭제용 이벤트 생성
- 매 새벽 4시마다 `partyAt` 이 6개월이 지난 파티들을 선별하는 스케쥴러 생성
- 해당하는 파티들이 존재하면, 이벤트에 추가하여 리스너에서 처리하도록 구현
- 스케쥴러에서 판별된 파티 삭제 진행
- 모든 연관관계를 먼저 끊은 후, 파티 삭제 진행
<br>
> ### 파티 삭제 스케쥴러에서 EventListener 선택 이유
- 삭제 대상을 판별하는 스케쥴러와, 실제 삭제를 진행하는 이벤트리스너를 나누어서 __책임 분리 및 관심사 분리, 코드 가독성 및 유지보수성 높임__. __단일 책임 원칙(SRP)__ 준수
- 이벤트리스너는 __트랜잭션의 바깥에서 작동__하므로, __하나의 파티 삭제에 실패해도 나머지에는 영향을 주지 않음__
- 지금 프로세스 대로면 별도의 로깅으로 실패 파티 ID를 얻을 수 있으므로, __후처리도 간편하며 모니터링하기도 좋음__
- __일괄 실패__ 시 EventListenerException을 발생시켜, __모든 처리가 진행되지 않은 이벤트 리스너 쪽의 문제임을 확실히 알 수 있음__
- 이후 이를 어떻게 처리할지, __후처리에 대한 확장성도 열려있음 (Kafka, 실패용 DB 추가, 알림 전송 등)__
> [FEAT] 6개월 지난 파티 일괄 삭제

- src/main/resources/logback-spring.xml
<br/>
<br/>
<br/>
- 파티 삭제 스케쥴러를 통한 정보가 기존 `party/delete` 폴더 내부에 잘 담기도록 수정
- 파티 관련 삭제 이벤트가 제대로 `info` 폴더와 `error` 폴더로 나뉠 수 있도록 수정
> [REFACTOR] 로그백 설정 수정

- src/main/java/com/ll/playon/domain/chat/dto/RemainMemberCountDto.java
- src/main/java/com/ll/playon/domain/chat/event/PartyRoomExpiredEvent.java
- src/main/java/com/ll/playon/domain/chat/event/PartyRoomUnusedEvent.java
- src/main/java/com/ll/playon/domain/chat/listener/PartyRoomEventListener.java
- src/main/java/com/ll/playon/domain/chat/repository/ChatMemberRepository.java
- src/main/java/com/ll/playon/domain/chat/repository/PartyRoomRepository.java
- src/main/java/com/ll/playon/domain/chat/scheduler/PartyRoomsScheduler.java
- src/main/java/com/ll/playon/domain/chat/service/ChatService.java
- src/main/java/com/ll/playon/domain/party/party/entity/Party.java
- src/main/java/com/ll/playon/domain/party/party/event/ExpiredPartyDetectedEvent.java
- src/main/java/com/ll/playon/domain/party/party/listener/PartyEventListener.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
- src/main/java/com/ll/playon/domain/party/party/scheduler/PartyScheduler.java
- src/main/java/com/ll/playon/domain/party/party/service/PartyService.java
<br/>
<br/>
<br/>
- 기존 `Listner` 에서 해결하던 방식은 파티가 시작되기만 하면 에러가 발생
- 이는 `ChatMember` 가 0보다 크기 때문에, 존재하는 모든 파티룸이 활성화된 상태면 이를 삭제할 수 없어서 설정해둔 `EventListenerException` 을 터트림
- 삭제 처리 이벤트에 등록할 판단 방식을 스케쥴러 내부에서 모두 하도록 변경
- `partyAt` 보다 __24시간__이 지난 파티룸을 삭제 판단하는 스케쥴링 추가
- 이에 따른 `Event` 및 `Listener` , 레코드 추가
- 파티룸 삭제 전, 파티의 상태를 `COMPLETED` 로 변경 및 `endedAt` 을 현재 시간으로 변경하도록 구현
- 쿼리의 조건이 추가됨에 따라, 이를 잘 활용할 수 있도록 기존의 `Party` 엔티티의 인덱스 필드 일부 변경
- 어울리지 않는 메서드명 및 검증, 중복 제거 등 리팩토링
> [FIX] 파티룸 스케쥴러 삭제 버그 수정

- src/main/java/com/ll/playon/domain/chat/listener/PartyRoomEventListener.java
- src/main/java/com/ll/playon/domain/chat/service/ChatService.java
- src/main/java/com/ll/playon/domain/party/party/listener/PartyEventListener.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
<br/>
<br/>
<br/>
- 로그 파일이 원하던 형식으로 저장되지 않고, 원하는 메서드에서의 로그만 저장되지 않던 문제 해결
- 기존 `partyRoom.getParty.closeParty()` 메서드에서 `Lazy Loading` 으로 인한 문제 발생
- 새로운 쿼리를 생성해서 직접적으로 `Party` 를 얻어와서 처리함으로 해당 문제 해결
> [FIX] 로그 파일 잘못된 형식 저장 해결 및 Lazy Loading으로 인한 문제 해결

- src/main/java/com/ll/playon/domain/board/repository/BoardRepository.java
- src/main/java/com/ll/playon/domain/board/service/BoardService.java
- src/main/java/com/ll/playon/domain/member/repository/MemberRepository.java
<br/>
<br/>
<br/>
- 게시글 상세 조회 최적화 및 N+1 방지
- Board 조회 시 Member Fetch Join 적용
- 대표 칭호 조회는 getProfile 쿼리로 처리
- Lazy Loading 방지 및 불필요한 쿼리 발생 방지
> [REFACTOR] 게시글 상세조회 프로필 이미지 버그 해결

- src/main/java/com/ll/playon/domain/member/service/MemberService.java
- src/main/java/com/ll/playon/domain/party/party/entity/Party.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
<br/>
<br/>
<br/>
- 기존 API : 종료된 공개 파티 중 로그가 작성된 것들만 가져오는 API
- 변경 : 종료된 파티를 가져오는 API
- 기존 API : 종료되지 않은 공개 파티를 가져오는 API
- 변경 : 종료된 파티를 가져오는 API
> [FIX] 종료된 파티만 가져오는 API로 변경

- src/main/java/com/ll/playon/domain/member/service/MemberService.java
- src/main/java/com/ll/playon/domain/party/party/repository/PartyRepository.java
<br/>
<br/>
<br/>
- 참가 신청자, 초대자인 경우에도 종료 파티가 보이는 버그 수정
- 참여 중인 파티를 파티 시작 시간 임박 순으로 정렬
> [FIX] 유저페이지 파티 및 종료 파티 노출 조건 수정
